/** @file */

#ifndef ERROR_H

#define ERROR_H

#include "../../primitives/s32.h"

/**
 * Indicates that no error has occurred.
 */
#define ERROR_NONE 0

/**
 * The error number readable by the hosting platform at the end of the current
 * event handler.  Positive values are generated by the game, while negative
 * values are generated by the engine.  Do not change this directly; use
 * @ref throw.  Automatically set to @ref ERROR_NONE at the start of each event
 * handler.
 */
extern s32 error;

/**
 * Call from anywhere to immediately halt execution with an error.  The hosting
 * runtime will NOT raise any further event handlers nor persist any buffers
 * until the game is fully restarted.
 * @param error The number of the error to raise.  Positive values are
 *              game-specific, while negative values are engine-specific.
 */
__attribute__((noreturn)) void throw(const s32 error);

#endif
