on:
  push:
    branches:
      - main

jobs:
  publish-api-documentation:
    if: github.repository == 'siliconspecter/indifference-engine'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: main

      - run: sudo apt-get install doxygen

      - run: doxygen
        working-directory: main/deliverables/documentation

      - uses: actions/checkout@v3
        with:
          repository: siliconspecter/indifference-engine-api-documentation
          path: pages
          ref: pages

      - run: find pages -mindepth 1 -maxdepth 1 -not -name ".git" -exec rm -r {} \;

      - run: cp -r main/deliverables/documentation/ephemeral/html/* pages

      - run: git config user.email siliconspecter@outlook.com
        working-directory: pages

      - run: git config user.name siliconspecter
        working-directory: pages

      - run: git add --all
        working-directory: pages

      - run: git diff --staged --quiet --exit-code || (git commit --message "Update pushed automatically."; git push)
        working-directory: pages
